### ISSUE TITLE
Some suggested improvements in coding instructions

### ISSUE THREAD

**Issue by sirockin** [quii/go-specs-greet#3]
Thank you for this really helpful extension to what was already a very useful book.

I've worked through the coding examples and had some points of friction:

1. I wasn't always clear on file locations and package names - in at least one case (`greet.go`) there is more than one file with the same name so some disambiguation is useful
2. On a couple of occasions there were superfluous imports in the code
3. It was slightly difficult to check against the final repository since the structure gets changed during the tutorial
4. The initially-specified implementations and invocations for StartDockerServer have `port`/`dockerFilePath` arguments swapped with respect to each other
5. There are some other minor variable naming errors

I have now worked through the tutorial again, correcting the points above in the README.md, and have raised a PR.

**Comment by quii** [comment]
> The initially-specified implementations and invocations for StartDockerServer have port/dockerFilePath arguments swapped with respect to each other

Yeah I was worried I messed up some things when I went back to retrospectively change things, sorry about that
