### ISSUE TITLE
Should extra unit tests be included in the specifications folder?

### ISSUE THREAD

**Issue by sirockin** [quii/go-specs-greet#6]
In [your example code for additional unit tests](https://github.com/quii/go-specs-greet/blob/696ac57c6c108f133d6675659f8c5546b97bc26c/greet_test.go#L17) you add the additional test in the unit test file invoked separately to the main specification.

Is there an argument to say that since this still represents *behaviour* of the system and according to some arguments our unit tests should also be driven by BDD principles, that even this aditional test should be included in the main specification as a subtest?

If we want to ensure a subtest is only run from unit tests, we could precede it with:

```go
if !testing.Short() {
    t.Skip()
}
```

**Comment by quii** [comment]
I guess so, but I'm not sure the specifications should have knowledge of how they're run, so I don't really _like_ seeing stuff like `t.Skip` in there, personally.
