### ISSUE TITLE
Suggestion: Provide guidance/examples on structuring specifications

### ISSUE THREAD

**Issue by sirockin** [quii/go-specs-greet#8]
This may be out of the scope of this chapter but it may be useful to provide guidance on how specifications should be structured as they become more complex, and in particular, how could such a structure map to BDD concepts and/or the key components of the Screenplay Pattern.

**Comment by sirockin** [comment]
I haven't tried modelling this but looking at the sample code, I imagine that 
- the `Greeter` and `MeanGreeter` interfaces and the drivers which implement them map to Screenplay `Abilities`.
- the methods of these interfaces map to `Interactions` and `Questions`
- the `GreetSpecification` and `CurseSpecification` functions, given the simplicity of the example look like they could be `Features`, `Scenarios` or even `Tasks`. I suppose that in a real application:
    - The exported specification method would represent  a `Feature` with each `Scenario` represented by a subtest. 
    - 'Tasks' would be created as non-exported helpers within the specification folder, called by each feature

**Comment by quii** [comment]
This is interesting stuff but my instinct with this chapter is it's _already_ got a lot to cover, if anything I want to remove stuff. Having a further chapter exploring the screenplay pattern would open the opportunity to use it with a slightly larger example too to illustrate the value.

**Comment by sirockin** [comment]
Understood. A further chapter on the subject would be great.
